### ISSUE TITLE
This should be moved to the parent ESAPI project

### ISSUE THREAD

**Issue by chrisisbeef** [ESAPI/node-esapi#1]
Hi Karl - this is awesome! I haven't seen some of this code in ages! :) I would love to move this project over to the official ESAPI Github and help foster some community involvement in the project!

https://github.com/ESAPI

If you would like to get this moving let me know and we'll get it moved over! Great work by the way!

**Comment by DeadAlready** [comment]
Thank you. 

Sure, we can move it so it is under the same umbrella that the others are.

**Comment by chrisisbeef** [comment]
Can you transfer the repository to me and I will move it to the ESAPI org, then add you to it

**Comment by chrisisbeef** [comment]
Can you transfer the repository to me and I will move it to the ESAPI org, then add you to the repo

**Comment by asnowfix** [comment]
It looks that this repo was actually transferred to parent ESAPI account, finally. This issue should be closed, I think.
