### ISSUE TITLE
Any CONTRIBUTING guidelines for node-esapi?

### ISSUE THREAD

**Issue by asnowfix** [ESAPI/node-esapi#3]
@DeadAlready & @chrisisbeef ,

The node-esapi repo does not contain any CONTRIBUTING.md guidelines. We (as a corporation) are preparing a PR bringing more code to node-esapi from owasp-esapi-js code (also adding bug fixes & a test harness), and are wondering wether we need to undergo any kind of constraint (document sign-off... etc) before submitting the code.

Thanks

**Comment by chrisisbeef** [comment]
I will leave it up to @DeadAlready as it's his project, we brought it
under the ESAPI umbrella a couple years ago to raise awareness of it's
existence and provide some consistency across the various
implementations and forks of the ESAPI project. @kwwall now runs the
ESAPI project proper and may have thoughts here as well.

**Comment by DeadAlready** [comment]
No real constraints from my side. Only that it follows the same coding style (4 space indentation and same line { etc ) and at least passes the measly test that are there at the moment.

**Comment by asnowfix** [comment]
Ok thank you.

**Comment by asnowfix** [comment]
After looking further in the code, we realized that node-esapi is about shipping the browser ESAPI code from a Node.js/Express server to a Browser. This is not what we want to achieve (run on Node.js), so I will close this issue & raise the question on the esapi-dev mailing instead.
