### ISSUE TITLE
encodeForJS is not a function.

### ISSUE THREAD

**Issue by SButzbach07** [ESAPI/node-esapi#8]
So I have been working on an chat project on Replit called [Butzbach Chat](https://replit.com/@SButzbach07/Butzbach-Chat) that used Node.js. It uses the Socket.IO library, which is very useful. I also have Express and HTTP modules installed. Then I got a comment about the website is open to XSS. So I looked it up and used OWASP's website for the DOM-based XSS cheat sheet. I came across the `node-esapi` module and I am using it. I imported the library using `ESAPI` as the variable name. I used `app.use(ESAPI.middleware());` to use ESAPI client scripts, and I used `org.owasp.esapi.ESAPI.initialize()` in the client script to use the functions. However, when I used `$ESAPI.encoder().encodeForJS()`, the developer console showed the following.
![Screenshot 2022-01-29 101912](https://user-images.githubusercontent.com/70033034/151666473-bf0e13d7-7275-40a3-884c-b6da32f5720e.png)
I am using the latest version of Google Chrome. I went to check `esapi.js` and found that the function doesn't exist.
![Screenshot 2022-01-29 101539](https://user-images.githubusercontent.com/70033034/151666352-57c12681-48bf-4e3b-b585-82882e798994.png)
I can use the other 2 functions for JavaScript, but can you add the `encodeForJS` definition for the client scripts?

**Comment by SButzbach07** [comment]
My testing code is in [Butzbach Chat Development](https://replit.com/@SButzbach07/Butzbach-Chat-Development).

**Comment by jeremiahjstacey** [comment]
Looking at the baseline there are actually 2 instances of the esapi.js file.

The one you appear to be referencing is 
https://github.com/ESAPI/node-esapi/blob/master/lib/public/esapi.js
In this file, you are correct.  The declaration of `encodeForJS` does not exist.

The other file is at the root of the lib directory
https://github.com/ESAPI/node-esapi/blob/master/lib/esapi.js

This version does contain the declaration on line 1081
```
        encodeForJavaScript: function(sInput) {
            return !sInput ? null : _javascriptCodec.encode(IMMUNE_JAVASCRIPT, sInput);
        },

        encodeForJavascript: this.encodeForJavaScript,

        encodeForJS: this.encodeForJavascript,
```

Is it possible to update the esapi.js reference being used to the one at the lib root?

**Comment by SButzbach07** [comment]
That's a negative. When the client connects, including refreshing the page, it recreates the client scripts from the source of where the scripts came. So, if you edit a script that has been created by the server, and you reload the page, it creates the original scripts, and your changes are lost. The client scripts from lib public, and it keeps recreating the scripts from that location, no matter when you edit the scripts. This is the same for Socket.IO, although I don't have a problem with that. The only way to solve this error is to fix the script in this repository.

**Comment by jeremiahjstacey** [comment]
I'd suggest creating a fork of the baseline, making the updates to duplicate the implementation from the lib root, and offer a PR for the update.

Looking at the [chat.js](https://replit.com/@SButzbach07/Butzbach-Chat-Development#chat/chat.js) file you've linked, it appears that both lines 28 and 40 use `encodeForJavaScript` already.  Line 6 is the only reference to `encodeForJS`.  Updating line 6 to match the other calls may also get past the problem in this case.

**Comment by xeno6696** [comment]
> That's a negative. When the client connects, including refreshing the page, it recreates the client scripts from the source of where the scripts came. So, if you edit a script that has been created by the server, and you reload the page, it creates the original scripts, and your changes are lost. The client scripts from lib public, and it keeps recreating the scripts from that location, no matter when you edit the scripts. This is the same for Socket.IO, although I don't have a problem with that. The only way to solve this error is to fix the script in this repository.

This is confusing.  

You can't alter where you're importing the esapi script?  

On deeper inspection @jeremiahjstacey it appears perhaps that the lib/public directory is intended to be the publicly released script--knowing nothing about Node conventions, it appears that the production build wasn't finished:  they added the function at the root script but didn't run the build necessary to propagate that script to the public directory.  

Not knowing how Node is supposed to handle this, I can't tell for sure if this is a mistake on esapi-node's part or of its a user error.

**Comment by SButzbach07** [comment]
> > That's a negative. When the client connects, including refreshing the page, it recreates the client scripts from the source of where the scripts came. So, if you edit a script that has been created by the server, and you reload the page, it creates the original scripts, and your changes are lost. The client scripts from lib public, and it keeps recreating the scripts from that location, no matter when you edit the scripts. This is the same for Socket.IO, although I don't have a problem with that. The only way to solve this error is to fix the script in this repository.
> 
> This is confusing.
> 
> You can't alter where you're importing the esapi script?
> 
> On deeper inspection @jeremiahjstacey it appears perhaps that the lib/public directory is intended to be the publicly released script--knowing nothing about Node conventions, it appears that the production build wasn't finished: they added the function at the root script but didn't run the build necessary to propagate that script to the public directory.
> 
> Not knowing how Node is supposed to handle this, I can't tell for sure if this is a mistake on esapi-node's part or of its a user error.

I'm not talking about altering the location of the script, I'm talking about altering the content of the script. When the page loads, it calls the function to get the scripts from the origin. If you edit the script, then reload, your changes are lost, because you're not writing to the original script, you're writing to the loaded script.

**Comment by SButzbach07** [comment]
> I'd suggest creating a fork of the baseline, making the updates to duplicate the implementation from the lib root, and offer a PR for the update.
> 
> Looking at the [chat.js](https://replit.com/@SButzbach07/Butzbach-Chat-Development#chat/chat.js) file you've linked, it appears that both lines 28 and 40 use `encodeForJavaScript` already. Line 6 is the only reference to `encodeForJS`. Updating line 6 to match the other calls may also get past the problem in this case.

Thank you. I fixed line 6 in `chat.js` and sent a pull request for the `esapi.js` lib public modification.

**Comment by xeno6696** [comment]
> I'm not talking about altering the location of the script, I'm talking about altering the content of the script. When the page loads, it calls the function to get the scripts from the origin. If you edit the script, then reload, your changes are lost, because you're not writing to the original script, you're writing to the loaded script.

Right, so from where I'm looking at things, your original error about "encodeforJS" not being a function, is tied directly to where it's getting imported in your clientside script.  By your own research

> I went to check esapi.js and found that the function doesn't exist.

That literally only happens in one case:  The function isn't in the script you loaded.  

@jeremiahjstacey pointed out that the function in question isn't in the `lib/public/esapi.js` file which you're clearly importing if the function doesn't exist there but DOES exist in `lib/esapi.js`  At this point, it's pure curiosity for me, but at some point you have to declare something like  `import * as ESAPI from '/lib/public/esapi.js';`  Why couldn't that be changed to  `import * as ESAPI from '/lib/esapi.js';` ?  I'm mainly asking because it seems an odd oversight to have skipped the wrapper for the publicly released version.  Just slamming it into the public version seems innocuous but this smells like something left out on purpose--I wish the node devs would chime in here.  

Is there a convention between browser code and server code where the namespaces have to be identical?   Why couldn't you just use encodeForJavascript?

**Comment by SButzbach07** [comment]
> > I'm not talking about altering the location of the script, I'm talking about altering the content of the script. When the page loads, it calls the function to get the scripts from the origin. If you edit the script, then reload, your changes are lost, because you're not writing to the original script, you're writing to the loaded script.
> 
> Right, so from where I'm looking at things, your original error about "encodeforJS" not being a function, is tied directly to where it's getting imported in your clientside script. By your own research
> 
> > I went to check esapi.js and found that the function doesn't exist.
> 
> That literally only happens in one case: The function isn't in the script you loaded.
> 
> @jeremiahjstacey pointed out that the function in question isn't in the `lib/public/esapi.js` file which you're clearly importing if the function doesn't exist there but DOES exist in `lib/esapi.js` At this point, it's pure curiosity for me, but at some point you have to declare something like `import * as ESAPI from '/lib/public/esapi.js';` Why couldn't that be changed to `import * as ESAPI from '/lib/esapi.js';` ? I'm mainly asking because it seems an odd oversight to have skipped the wrapper for the publicly released version. Just slamming it into the public version seems innocuous but this smells like something left out on purpose--I wish the node devs would chime in here.
> 
> Is there a convention between browser code and server code where the namespaces have to be identical? Why couldn't you just use encodeForJavascript?

The `README.md` file never said anything about an `import` statement. Also, in the file directory it doesn't show `/lib/whatever/else/is/in/the/folder`. This is what the directory shows for the page.
![image](https://user-images.githubusercontent.com/70033034/151737022-10509735-d84a-43ac-8960-5cfdc9a5ece3.png)
`build/esm` deals with Socket.IO.
The huge UUID-named folder is created by a web security program on my PC. Unrelated to the project.
`node_modules` is pretty much self-explanatory.
The only folder left is `esapi`, which has the `/lib/public/esapi.js` file loaded, still without `encodeForJS`. After examining `utils.js` in `/lib`, the middleware function imports `esapi.js` from `/lib/public/`.
![image](https://user-images.githubusercontent.com/70033034/151737461-3a13ea33-0edb-437a-80c8-82120f02f024.png)

**Comment by SButzbach07** [comment]
I have pushed a pull request to commit `esapi.js` in `/lib/public` with my changes, specifically adding the definition for `encodeForJS`.

**Comment by jeremiahjstacey** [comment]
@SButzbach07 - I'm hoping to have feedback from one of the listed project contributors before merging. I've added a comment to the PR to prompt that interaction.  Barring feedback I intend to merge the change next weekend -- hopefully a week is enough time for others to get eyes on the modification.

**Comment by kwwall** [comment]
@SButzbach07 @jeremiahjstacey @xeno6696 - Sorry I'm late to the party, but has anyone considered that maybe just the OWASP Cheatsheet that @SButzbach07 is incorrect and instead should have used `$ESAPI.encoder().encodeForJavascript()`? Or am I just missing something. `Encoder.encodeForJavaScript` is what it is called in the other ESAPI implementations as well. If that's the case, we should fix the Cheat Sheet rather than hack **node-esapi** to accommodate it.

**Comment by jeremiahjstacey** [comment]
@kwwall That had crossed my mind.  The thing that was confusing to me was the implementation similarities between the two esapi.js files.
If there were no reference to the encodeForJS method in the baseline, then it would have been cut and dry in my mind.  Since the delegation does appear in one and is lacking in the other, the course of resolution is less clear to me.

If nothing else this modification is adding consistency to the files in the baseline, which I'd think would be useful for maintenance. 

That being said, you're right.  This change is not required, it's convenience.  If the consistency aspect of the two esapi.js files is desired and intended, then I agree this change can be rejected.

**Comment by SButzbach07** [comment]
Got it.

**Comment by xeno6696** [comment]
@kwwall I was wondering if maybe it wasn't just a missing definition?  I agree that its a convenience method, but speaking for me personally, I'd rather type "encodeForJS()" then the whole message.  (But then again, I don't use IDEs when programming javascript.)
